on: push
name: CI
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install
      run: npm install
    - name: Lint
      run: npm run lint
    env:
      CI: true
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: Install
      run: npm install
    - name: Test
      run: npm test
    env:
      CI: true